### ISSUE TITLE
Improve installation procedure

### ISSUE THREAD

**Issue by bouweandela** [DynaSlum/satsense#15]
- Make it possible to install satsense with `pip`. [Upload from travis](https://docs.travis-ci.com/user/deployment/pypi)?
- Create a package on conda-forge too?

**Comment by bpmweel** [comment]
Conda-forge would be handy for the binary packages such as
- NetCDF
- GDAL

**Comment by bouweandela** [comment]
Related #28

**Comment by bpmweel** [comment]
done.
