### ISSUE TITLE
Clean up notebooks

### ISSUE THREAD

**Issue by bouweandela** [DynaSlum/satsense#17]
**As a** Remote sensing expert user of satsense
**I would like to** Have an example notebook showing how to use satsense
**because** I can use this as a starting point for my own research.

Most notebooks are outdated. Update or remove once we have a more stable API.

This notebook is most informative and relatively up to date:
satsense/notebooks/demo_notebooks/Classification/Simple Example.ipynb

**Comment by bouweandela** [comment]
Related #30

**Comment by bouweandela** [comment]
Got started on updating 'notebooks/demo_notebooks/Classification/Simple\ Example.ipynb' in the `notebooks` branch.

**Comment by bpmweel** [comment]
done.
