### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by bpmweel** [DynaSlum/satsense#25]
**As a** remote sensing user of satsense
**I would like to** be able to look up how to use the relevant parts of satsense in the documentation
**because** without documentation using satsense will be very hard

- [x] Check public interface for docstrings
- [x] Example Jupyter Notebooks #17
- [x] Write User Guide
- [x] Readthedocs documentation (sphinx)

Estimate: 8 (timeboxed to 5)

**Comment by bouweandela** [comment]
We should use setuptools integration to make the command `python setup.py build_sphinx` work. 

These packages should be added under the 'dev' extra in setup.py:
'sphinx',
'sphinx_rtd_theme',

Sphinx configuration options should be set in setup.cfg, see https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

**Comment by bouweandela** [comment]
Our documentation is now available on [readthedocs](https://satsense.readthedocs.io/en/latest/). For testing updates, use the [`doc`](https://satsense.readthedocs.io/en/doc/) branch.

**Comment by bpmweel** [comment]
Move unused Jupyter Notebooks to a draft-notebook branch

**Comment by bpmweel** [comment]
Done.
