### ISSUE TITLE
Create automated pypi release

### ISSUE THREAD

**Issue by bpmweel** [DynaSlum/satsense#28]
We should make sure the version is set correctly

**Comment by bouweandela** [comment]
Blog about automated releases: https://hypothesis.works/articles/continuous-releases/

**Comment by bouweandela** [comment]
Some information about versioning: https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by bouweandela** [comment]
Best is to upload the package to PyPi with your own account and add the `nlesc` user owner role.
